println(true,);
println(not true,);
println(not not true,);
println(not not not true,);
println(not not not false,);
println(89,);
println(-89,);
println(--89,);
println(---89,);
println(2.34,);
println(-2.34,);