// Code generated by "stringer -type=IdentifierType"; DO NOT EDIT.

package evaluator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidIdentifier - -1]
	_ = x[ConstantIdentifier-0]
	_ = x[VariableIdentifier-1]
	_ = x[FunctionIdentifier-2]
}

const _IdentifierType_name = "InvalidIdentifierConstantIdentifierVariableIdentifierFunctionIdentifier"

var _IdentifierType_index = [...]uint8{0, 17, 35, 53, 71}

func (i IdentifierType) String() string {
	i -= -1
	if i < 0 || i >= IdentifierType(len(_IdentifierType_index)-1) {
		return "IdentifierType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _IdentifierType_name[_IdentifierType_index[i]:_IdentifierType_index[i+1]]
}
