// Code generated by "stringer -type=BlockKind"; DO NOT EDIT.

package blockkind

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FreeFloating-0]
	_ = x[If-1]
	_ = x[Else-2]
	_ = x[For-3]
}

const _BlockKind_name = "FreeFloatingIfElseFor"

var _BlockKind_index = [...]uint8{0, 12, 14, 18, 21}

func (i BlockKind) String() string {
	if i < 0 || i >= BlockKind(len(_BlockKind_index)-1) {
		return "BlockKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlockKind_name[_BlockKind_index[i]:_BlockKind_index[i+1]]
}
