// Code generated by "stringer -type=VariableType"; DO NOT EDIT.

package visitor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Var-1]
	_ = x[Const-2]
	_ = x[Func-3]
}

const _VariableType_name = "InvalidVarConstFunc"

var _VariableType_index = [...]uint8{0, 7, 10, 15, 19}

func (i VariableType) String() string {
	if i < 0 || i >= VariableType(len(_VariableType_index)-1) {
		return "VariableType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VariableType_name[_VariableType_index[i]:_VariableType_index[i+1]]
}
