printline(true);
printline(not true);
printline(not not true);
printline(not not not true);
printline(not not not false);
printline(89);
printline(-89);
printline(--89);
printline(---89);
printline(2.34);
printline(-2.34);
printline(--2.34);
printline(---2.34);
